apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: student-259257
data:
  MONGODB_RW_HOST: "mongodb-rw-service"
  MONGODB_RO_HOST: "mongodb-ro-service"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: student-259257
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==  # "root" zakodowane w base64
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ== # "example" base64 encoded