apiVersion: v1
kind: Service
metadata:
  name: mongodb-ro-service
  namespace: student-259257
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
  clusterIP: None
  publishNotReadyAddresses: true

#apiVersion: v1
#kind: Service
#metadata:
#  name: mongodb-ro-service
#  namespace: student-259257
#spec:
#  clusterIP: None
#  selector:
#    app: mongodb
#    role: ro