apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backup-pv
  namespace: student-259257
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

#spec:
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  hostPath:
#    path: "/mnt/mongo-backup"